function [ output ] = dynamic( input )
%DYNAMIC Dynamic equations of the model
%   Function takes current control inputs, as well as velocities
%   vector generated by itself in the previous iteration, as inputs and
%   gives vector of velocities of the vehicle in the body frame as an
%   output.

%Light vehicle
% m11=19;
% m22=34;
% m33=2.1;
% m23=0;
% m32=0;
% d11=2.4;
% d22=23;
% d33=9.7;
% d23=0;
% d32=0;

%Heavy vehicle
m11=215;
m22=265;
m33=80;
m23=0;
m32=0;
d11=70;
d22=100;
d33=100;
d23=0;
d32=0;

l=1;

Tau_u=input(1);
Tau_r=input(2);
zeta_3=input(3);%u
zeta_4=input(4);%v
z2=input(5);%r
z1=input(6);%psi

u=zeta_3*cos(z1)+zeta_4*sin(z1);
v=-zeta_3*sin(z1)+zeta_4*cos(z1)-z2*l;

a=((m22*v+m23*z2)*z2-d11*u)/m11-(v*z2-l*z2^2);
b=u*z2+((-(m11*m33-m23^2)/(m22*m33-m23^2))*u+(d33*m23-d23*m33)/(m22*m33-m23^2))*z2+(-(((m11-m22)*m23)/(m22*m33-m23^2))*u-(d22*m33-d32*m23)/(m22*m33-m23^2))*v+(((m23*d22-m22*(d32+(m22-m11)*u))*v+(m23*(d23+m11*u)-m22*(d33+m23*u))*z2)/(m22*m33-m23^2))*l;

F=[cos(z1) -sin(z1); sin(z1) cos(z1)]*[a;b];
F1=F(1);
F2=F(2);

zeta_3_dot=F1+cos(z1)*Tau_u-l*sin(z1)*Tau_r;
zeta_4_dot=F2+sin(z1)*Tau_u+l*cos(z1)*Tau_r;
z2_dot=((m23*d22-m22*(d32+(m22-m11)*u))*v+(m23*(d23+m11*u)-m22*(d33+m23*u))*z2)/(m22*m33-m23^2)+Tau_r;

output=[zeta_3_dot; zeta_4_dot; z2_dot];
end

