function [ output ] = kinematic( input )
%KINEMATIC Kinematic equations of the model
%   Function takes vector of velocities of the vehicle in the body frame 
%   [u; v; r], generated by the dynamic block and angle psi, generated by 
%   itself in the previous iteration, as inputs and gives current 
%   velocities in x, y axis, as well as angular velocity psi as an output.

V_x=0.05;
V_y=-0.08;

zeta_3=input(1);
zeta_4=input(2);
z2=input(3);
psi=input(4);

zeta_1_dot=zeta_3+V_x;
zeta_2_dot=zeta_4+V_y;
z1_dot=z2;


% x_dot=u*cos(psi)-v*sin(psi)+V_x;
% y_dot=u*sin(psi)+v*cos(psi)+V_y;

% x_dot=u*cos(psi)-v*sin(psi);
% y_dot=u*sin(psi)+v*cos(psi);
% psi_dot=r;

% 
% output=[x_dot; y_dot; psi_dot];

output=[zeta_1_dot; zeta_2_dot; z1_dot];

end

