function [ output ] = kinematic( input )
%KINEMATIC Kinematic equations of the model
%   Function takes vector of velocities of the vehicle in the body frame 
%   [u; v; r], generated by the dynamic block and angle psi, generated by 
%   itself in the previous iteration, as inputs and gives current 
%   velocities in x, y axis, as well as angular velocity psi as an output.

u=input(1);
v=input(2);
r=input(3);
psi=input(4);

x_dot=u*cos(psi)-v*sin(psi);
y_dot=u*sin(psi)+v*cos(psi);
psi_dot=r;


output=[x_dot; y_dot; psi_dot];

end

